### ISSUE TITLE
It doesn't seem to work

### ISSUE THREAD

**Issue by 850tomato** [deleterium/Signum-D-Or#1]
![tem](https://user-images.githubusercontent.com/36918334/130348152-6cc5e3e6-54c6-4b7a-9124-1bc893feb152.png)
I paste a piece of code of byteocde(transform from solidity)，and I chick the button, but It doesn't have respond.

**Comment by deleterium** [comment]
The decompiler is specific for signum https://signum.network You will need to create the program with tools for signum, like SmartC, SmartJ or SmartContractor.

Or get a contract from signum blockchain to inspect: https://europe.signum.network/burst?requestType=getATDetails&at=15264211719755489695

As I know, solidity creates software for ethereum.
